version: "3.3"

services:
    signal_server:
      build: ./WebRTCSignal


    nginx:
        image: nginx:1.23.1-alpine
        restart: always
        #network_mode: host
        ports:
          - "8443:443"

        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./ssl:/ssl/
          - ./webrtc-min-client/dist:/usr/share/nginx/html/
