version: "3.3"

services:
    # janus_server:
    #     image: registry.timephone.org:5000/janus:1.0.4
    #     network_mode: host
    #     volumes: 
    #       - ./conf:/opt/janus/etc/janus
    #     ulimits:
    #       nproc: 65535
    #       nofile:
    #         soft: 100000
    #         hard: 100000
    #     restart: always

    nginx:
        image: nginx:1.23.1-alpine
        restart: always
        #network_mode: host
        ports:
          - "8443:443"

        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./ssl:/ssl/
          - ./webrtc-min-client/dist:/usr/share/nginx/html/
