version: "3.3"

services:
    signal_server:
      image: registry.timephone.org:5000/wrtsig
      restart: always
      network_mode: host

    nginx:
      image: nginx:1.23.1-alpine
      restart: always
      network_mode: host

      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /ssl:/ssl/
        - ./html:/usr/share/nginx/html/
